name: Install, test, and build

on: [push, pull_request]

jobs:
  install_test_build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 14.x
      - name: npm install
        run: |
          npm ci
      - name: npm test
        run: |
          npm test
        env:
          CI: true
      - name: npm build
        run: |
          npm run build
